name: Comby Action
description: Run comby on your repository
author: Rijnard van Tonder

inputs:
    match_template:
        description: A match template.
        required: true
    rewrite_template:
        description: A rewrite template.
        required: true

runs:
    using: docker
    image: Dockerfile
    env:
        COMBY_M: ${{ inputs.match_template }}
        COMBY_R: ${{ inputs.rewrite_template }}
