name: Comby Action
description: Run comby on your repository
author: Rijnard van Tonder

inputs:
    args:
        description: 'comby command line args'
        required: true
        default: '-help'
outputs:
    exit-code:
        description: 'The exit code of the script. Emits exit code 2 if files were rewritten.'

runs:
    using: docker
    image: Dockerfile
    args:
        - ${{ inputs.args }}
branding:
    icon: 'code'
    color: 'orange'
