name: Comby Action
description: Run comby on your repository
author: Rijnard van Tonder

inputs:
    config:
        description: A URL for a configuration file. If unset, will look for .comby in the repo.

runs:
    using: docker
    image: Dockerfile
    env:
        COMBY_CONFIG: ${{ inputs.config }}
